### ISSUE TITLE
A shared @SequenceGenerator not found when referenced from other entities

### ISSUE THREAD

**Issue by sakaal** [jpdigital/hibernate5-ddl-maven-plugin#17] opened 2017-10-14 17:59 UTC
On hibernate50-ddl-maven-plugin version 2.1.0-beta.1

We are using `@SequenceGenerator` and `@GeneratedValue` annotations like this:

```
@SequenceGenerator(name = "key_gen", sequenceName = "key_sequence")
public class SomeEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "key_gen")
    private long key;
```

This works fine when the `@SequenceGenerator` is defined in the same entity class. However, when trying to reference the same generator by name from other entities when generating schemas using the plugin, the generator is not found. Perhaps the code is interpreted in such order that the `@SequenceGenerator` annotation has not been encountered yet when the plugin already tries to interpret the first `@GeneratedValue` annotation referencing it?

As a workaround we are currently defining a different generator for each entity that uses a generated primary key. We would like to share the same generator between multiple entities because it's simpler.

**Comment by jpdigital** [comment] 2018-03-03 15:52
I just investigated this issue and was able to reproduce it. It looks like the problem is caused by Hibernate and not by the plugin. The plugin itself is only a "frontend" for Hibernates APIs for schema generation.

After some research I'm not sure if it is possible to define the a sequence generator in one class and than use it in another class. What works is to repeat the some `@SequenceGenerator` in all classes which should use the same sequence. 

I will investigate this further, but I'm afraid want you want to do is not possible with Hibernate.

**Comment by jpdigital** [comment] 2020-06-18 17:53
Closing this issue because of its age. If the problem persists please open a new issue.

**Closed by jpdigital** 2020-06-18 17:53 UTC
