### ISSUE TITLE
scale, precision or @Size for numeric types (ORACLE DIALECTS)

### ISSUE THREAD

**Issue by yuxblank** [jpdigital/hibernate5-ddl-maven-plugin#31] opened 2020-02-19 16:59 UTC
I can't make @Column properties for defining numbers length to work.
I tried both scale, precision or even length but it doesn't seems to work.
Also @Size annotation from javax.validation does not apply.
Im using only JPA annotations.

for exampe:
```java     
@Id
    @SequenceGenerator(name = "ROSURVEY_GEN",allocationSize = 1,sequenceName = "ROSURVEY_SEQ")
    @GeneratedValue(generator = "ROSURVEY_GEN",strategy = GenerationType.SEQUENCE)
    @Column(name = "IDSURVEY",scale = 18, nullable = false)
    @Size(max = 18)
    protected Long id;
``` 

does produces:

`    create table TABLE(
        IDSURVEY number(19,0) not null,
       .....
`

Tested with both ORACLE10G, ORACLE12C

**Comment by jpdigital** [comment] 2020-06-18 18:11
Not a bug in the plugin. As defined JPA specification `scale` and `precision` are only used if the column is a decimal column. This is the case if you use `BigDecimal` instead of `Long`. Also, at least with Hibernate, `scale` has only an effect if `precision` is also set.

Since this is not a bug in plugin I'm closing the issue.

**Closed by jpdigital** 2020-06-18 18:11 UTC
